services:
#    pdf_js_viewer.example:
#        class: PDFjsViewerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    pdfjs_viewer.viewer_controller:
        class: PDFjsViewerBundle\Controller\ViewerController
        calls:
             - [setContainer, ["@service_container"]]